<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ExcelMerge</RootNamespace>
    <AssemblyName>ExcelMerge</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetDiff\NetDiff\NetDiff.csproj" />
  </ItemGroup>
</Project>
