<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExcelMerge.Domain\ExcelMerge.Domain.csproj" />
    <ProjectReference Include="..\ExcelMerge.Storage\ExcelMerge.Storage.csproj" />
  </ItemGroup>
</Project>
